services:
  # idp-server:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "2345:2345"
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - idp-db:/var/lib/postgresql/data

volumes:
  idp-db:
    driver: local
